2024-10-27 11:12:40,094 - WARNING - Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
2024-10-27 11:12:40,111 - WARNING -  * Debugger is active!
2024-10-27 11:12:40,125 - INFO -  * Debugger PIN: 883-533-741
2024-10-27 11:12:40,329 - INFO - Client connected
2024-10-27 11:12:40,330 - INFO - 127.0.0.1 - - [27/Oct/2024 11:12:40] "GET /all-images HTTP/1.1" 200 -
2024-10-27 11:12:40,332 - INFO - 127.0.0.1 - - [27/Oct/2024 11:12:40] "GET /all-images HTTP/1.1" 200 -
2024-10-27 11:12:40,377 - INFO - 127.0.0.1 - - [27/Oct/2024 11:12:40] "[36mGET /images/nvcamtest_7563_s00_00168%202.jpg HTTP/1.1[0m" 304 -
2024-10-27 11:15:42,407 - INFO - Client disconnected. Reason: unknown
2024-10-27 11:15:42,408 - INFO - 127.0.0.1 - - [27/Oct/2024 11:15:42] "[35m[1mGET /socket.io/?EIO=4&transport=websocket HTTP/1.1[0m" 500 -
2024-10-27 11:15:42,410 - ERROR - Error on request:
Traceback (most recent call last):
  File "/Users/aahil/Edhitha/edhithaGCS/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/Users/aahil/Edhitha/edhithaGCS/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 336, in execute
    write(b"")
  File "/Users/aahil/Edhitha/edhithaGCS/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 261, in write
    assert status_set is not None, "write() before start_response"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: write() before start_response
2024-10-27 11:15:42,571 - INFO - 127.0.0.1 - - [27/Oct/2024 11:15:42] "GET /all-images HTTP/1.1" 200 -
2024-10-27 11:15:42,573 - INFO - Client connected
2024-10-27 11:15:42,574 - INFO - 127.0.0.1 - - [27/Oct/2024 11:15:42] "GET /all-images HTTP/1.1" 200 -
2024-10-27 11:15:42,584 - INFO - 127.0.0.1 - - [27/Oct/2024 11:15:42] "[36mGET /images/nvcamtest_7563_s00_00168%202.jpg HTTP/1.1[0m" 304 -
2024-10-27 11:18:05,268 - INFO - Client disconnected. Reason: unknown
2024-10-27 11:18:05,269 - INFO - 127.0.0.1 - - [27/Oct/2024 11:18:05] "[35m[1mGET /socket.io/?EIO=4&transport=websocket HTTP/1.1[0m" 500 -
2024-10-27 11:18:05,270 - ERROR - Error on request:
Traceback (most recent call last):
  File "/Users/aahil/Edhitha/edhithaGCS/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/Users/aahil/Edhitha/edhithaGCS/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 336, in execute
    write(b"")
  File "/Users/aahil/Edhitha/edhithaGCS/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 261, in write
    assert status_set is not None, "write() before start_response"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: write() before start_response
2024-10-27 11:18:05,508 - INFO - Client connected
2024-10-27 11:18:05,512 - INFO - 127.0.0.1 - - [27/Oct/2024 11:18:05] "GET /all-images HTTP/1.1" 200 -
2024-10-27 11:18:05,518 - INFO - 127.0.0.1 - - [27/Oct/2024 11:18:05] "GET /all-images HTTP/1.1" 200 -
2024-10-27 11:18:05,527 - INFO - 127.0.0.1 - - [27/Oct/2024 11:18:05] "[36mGET /images/nvcamtest_7563_s00_00168%202.jpg HTTP/1.1[0m" 304 -
